/* Club detail page. */
(function (global) { 'use strict';
  var state = { id: '', club: null, members: [], member: false, admin: false, tab: 'feed' }, root;
  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
  function hasToken() { try { return !!(typeof global.getToken === 'function' ? global.getToken() : localStorage.getItem('mp_site_token')); } catch (_) { return false; } }
  function toast(m,o) { try { if (global.showToast) global.showToast(m,o); } catch (_) {} }
  function req(path, opts) {
    if (hasToken() && typeof global.api === 'function') return global.api(path, opts);
    var base=global.API_BASE||global.SITE_ORIGIN||'https://movie-planner.ru';
    return fetch(base+path,{headers:{Accept:'application/json'},credentials:'same-origin'}).then(function(r){return r.json().catch(function(){return {};}).then(function(d){if(!r.ok){throw new Error((d&&d.error)||('HTTP '+r.status));}return d;});});
  }
  function arr(d, keys) { if (Array.isArray(d)) return d; for(var i=0;i<keys.length;i++) if(d&&Array.isArray(d[keys[i]])) return d[keys[i]]; return []; }
  function fmt(v) { if(!v) return ''; var d=new Date(v); return isNaN(d.getTime())?String(v):d.toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}); }
  function poster(x) { return (x&&(x.poster||x.poster_url||x.cover_url))||((x&&(x.kp_id||x.id))?'/api/public/poster/kp/st/images/film_iphone/iphone360_'+String(x.kp_id||x.id).replace(/\D/g,'')+'.jpg':''); }
  function title(x) { return String(x&&(x.title||x.film_title||x.name)||'Фильм'); }
  function link(x) { var id=x&&(x.kp_id||x.kinopoisk_id||x.id); return id?'/f/'+encodeURIComponent(String(id)):''; }
  function norm(x) { x=x||{}; var p=x.next_plan||x.upcoming_plan||x.next_watch||x.next; var ps=x.next_plans||x.upcoming_plans||x.schedule||[]; if(!Array.isArray(ps))ps=ps?[ps]:[]; if(p&&!ps.length)ps=[p]; var rw=x.recent_watched||x.last_watched||x.recent_films||[]; if(!Array.isArray(rw))rw=rw?[rw]:[]; return { raw:x,id:x.chat_id||x.id||state.id,name:x.name||x.display_name||'Киноклуб',description:x.description||x.short_description||x.about||'',cover:x.cover_url||x.cover||x.photo_url||'',emoji:x.emoji||x.group_emoji||'🎬',members:Number(x.members_count!=null?x.members_count:(x.member_count!=null?x.member_count:x.members))||0,films:Number(x.watched_count||x.watches_count||x.films_count)||0,frequency:x.watch_frequency_label||x.frequency_label||x.watch_cadence||'',plans:ps,recent:rw,owner:x.owner_id||x.creator_id||null}; }
  function ids() { var out=[]; try { out.push(String(localStorage.getItem('mp_site_active_chat_id')||'')); var ss=JSON.parse(localStorage.getItem('mp_site_sessions')||'[]'); (ss||[]).forEach(function(s){if(s)out.push(String(s.user_id||s.chat_id||''));}); } catch (_) {} return out; }
  function detect() { var ci=ids(), raw=state.club.raw||{}, st=String(raw.membership||raw.my_membership||raw.join_status||raw.status||'').toLowerCase(); state.member=!!(raw.is_member||raw.i_am_member||['member','joined','approved'].indexOf(st)>=0||state.members.some(function(m){return m.is_current||m.current||m.me||[m.user_id,m.chat_id,m.id].some(function(i){return i!=null&&ci.indexOf(String(i))>=0;});})); state.admin=!!(raw.is_admin||raw.is_owner||raw.owner===true||['admin','administrator','owner','creator'].indexOf(st)>=0); state.members.forEach(function(m){var r=String(m.role||m.member_role||m.status||'').toLowerCase();if((m.is_current||m.current||m.me)&&['admin','administrator','owner','creator'].indexOf(r)>=0)state.admin=true;}); }
  function empty(h,p) { return '<div class="club-empty"><div class="club-empty-icon">✦</div><h3>'+esc(h)+'</h3><p>'+esc(p)+'</p></div>'; }
  function btn(id,label) { return '<button type="button" class="club-tab'+(state.tab===id?' is-active':'')+'" data-club-tab="'+id+'">'+label+'</button>'; }
  function schedule() { var rows=state.club.plans.map(function(p){var im=poster(p), l=link(p), t=title(p), dt=p.plan_datetime||p.when||p.date||p.planned_at||p.starts_at||p.watch_at;return '<article class="club-schedule-item">'+(im?'<img src="'+esc(im)+'" alt="" loading="lazy">':'<div class="club-poster-empty">🎬</div>')+'<div><div class="club-when">'+esc(fmt(dt))+'</div><h3>'+(l?'<a href="'+esc(l)+'">'+esc(t)+'</a>':esc(t))+'</h3><p>'+esc(p.location||p.place||p.format||'План клуба')+'</p>'+(state.member&&p.zoom_url?'<p><a href="'+esc(p.zoom_url)+'" rel="noopener">Ссылка на обсуждение</a></p>':(p.zoom_url?'<p>Ссылка скрыта · вступите в клуб</p>':''))+'</div>'+(state.member?'<span class="club-status">✓ В плане</span>':'<button type="button" class="club-mini-btn" data-club-join>Вступить</button>')+'</article>';}).join(''); return '<section class="club-panel'+(state.tab==='schedule'?' is-active':'')+'" data-club-panel="schedule">'+(rows||empty('Расписание пока пусто','Ближайшие планы клуба появятся здесь.'))+'</section>'; }
  function films() { var cards=state.club.recent.map(function(f){var im=poster(f),l=link(f);return '<article class="club-film-card">'+(im?'<img src="'+esc(im)+'" alt="" loading="lazy">':'<div class="club-film-empty">🎬</div>')+'<div class="club-film-title">'+(l?'<a href="'+esc(l)+'">'+esc(title(f))+'</a>':esc(title(f)))+'</div><div class="club-film-meta">'+esc(fmt(f.watched_at||f.date||f.watched_on)||'Просмотр клуба')+'</div></article>';}).join('');return '<section class="club-panel'+(state.tab==='films'?' is-active':'')+'" data-club-panel="films"><p class="club-panel-hint">Только фильмы из данных клуба — без выдуманной сетки.</p>'+(cards?'<div class="club-films">'+cards+'</div>':empty('Пока нет фильмов','Здесь появятся подтверждённые просмотры клуба.'))+'</section>'; }
  function members() { var rows=state.members.map(function(m){var n=m.name||m.display_name||m.username||m.first_name||'Участник',av=m.photo_url||m.avatar_url||'',r=String(m.role||m.member_role||m.status||'').toLowerCase();return '<div class="club-member">'+(av?'<img src="'+esc(av)+'" alt="">':'<div class="club-avatar">'+esc(n.slice(0,1))+'</div>')+'<div><b>'+esc(n)+'</b><span>'+esc(r==='owner'||r==='creator'?'создатель':r==='admin'||r==='administrator'?'админ':'участник')+'</span></div></div>';}).join('');return '<section class="club-panel'+(state.tab==='members'?' is-active':'')+'" data-club-panel="members">'+(rows?'<div class="club-members">'+rows+'</div>':empty('Участники скрыты',hasToken()?'Список участников пока не загрузился.':'Войдите, чтобы увидеть участников клуба.'))+'</section>'; }
  function render() { if(!root||!state.club)return; var c=state.club, settings=state.admin; root.innerHTML='<div class="club-page"><div class="club-layout"><aside class="club-aside"><div class="club-hero">'+(c.cover?'<img class="club-cover-img" src="'+esc(c.cover)+'" alt="">':'<div class="club-cover-empty">'+esc(c.emoji)+'</div>')+'<h1>'+esc(c.name)+'</h1><p class="club-sub">Публичный киноклуб'+(c.frequency?' · '+esc(c.frequency):'')+'</p><div class="club-stats"><span class="club-stat"><b>'+esc(c.members||'—')+'</b> участника</span><span class="club-stat"><b>'+esc(c.films||'—')+'</b> фильмов</span></div><div class="club-actions"><button type="button" class="club-btn club-btn-primary" data-club-join'+(state.member?' disabled':'')+'>'+(state.member?'Вы в клубе':'Вступить')+'</button><button type="button" class="club-btn club-btn-ghost" data-club-share>Поделиться</button>'+(settings?'<button type="button" class="club-btn club-btn-ghost" data-club-tab-jump="settings">Настройки</button>':'')+'</div></div>'+(c.description?'<div class="club-about"><h2>О клубе</h2><p>'+esc(c.description)+'</p></div>':'')+'<div class="club-chips">'+(c.films?'<span>🎞 '+esc(c.films)+' просмотров клуба</span>':'')+(c.members?'<span>👥 '+esc(c.members)+' участников</span>':'')+(c.frequency?'<span>◷ '+esc(c.frequency)+'</span>':'')+'</div></aside><main class="club-main"><nav class="club-tabs" role="tablist">'+btn('feed','Лента')+btn('schedule','Расписание')+btn('films','Фильмы')+btn('members','Участники')+btn('stats','Статистика')+(settings?btn('settings','Настройки'):'')+'</nav><section class="club-panel'+(state.tab==='feed'?' is-active':'')+'" data-club-panel="feed">'+empty('Пока нет постов','Лента клуба появится, когда появятся посты и обсуждения.')+'</section>'+schedule()+films()+members()+'<section class="club-panel'+(state.tab==='stats'?' is-active':'')+'" data-club-panel="stats">'+(c.films?'<div class="club-highlight"><div><span>Просмотры клуба</span><b>'+esc(c.films)+'</b></div><div><span>Участники</span><b>'+esc(c.members||'—')+'</b></div></div>':empty('Статистика появится позже','Нужны подтверждённые просмотры и оценки участников клуба.'))+'</section>'+(settings?'<section class="club-panel'+(state.tab==='settings'?' is-active':'')+'" data-club-panel="settings"><div class="club-settings-card"><h3>Настройки клуба</h3><p>Управление профилем, приватностью и участниками подключим после появления granular ACL.</p><button type="button" class="club-mini-btn" data-club-copy>Скопировать инвайт</button></div></section>':'')+'<p class="club-note">Посты, опросы и реакции появятся после подключения activity API.</p></main></div></div>'; bind(); }
  function login() { try { sessionStorage.setItem('mp_oauth_return',location.pathname+location.search+location.hash); } catch (_) {} if(typeof global.requireAuthForAction==='function')global.requireAuthForAction('Войдите, чтобы вступить в киноклуб'); else if(typeof global.showLoginModalOverlay==='function')global.showLoginModalOverlay(); }
  function join() { if(state.member)return; if(!hasToken()){login();return;} var b=root.querySelector('[data-club-join]');if(b){b.disabled=true;b.textContent='Отправляем…';} global.api('/api/site/rooms/'+encodeURIComponent(state.id)+'/join-request',{method:'POST',body:'{}'}).then(function(d){var ok=d&&(d.status==='approved'||d.joined===true||d.is_member===true);toast(ok?'Вы вступили в киноклуб':'Заявка отправлена');state.member=ok;render();}).catch(function(e){if(b){b.disabled=false;b.textContent='Вступить';}toast((e&&e.message)||'Не удалось отправить заявку',{type:'error'});}); }
  function copy() { var v='https://movie-planner.ru/club/'+encodeURIComponent(state.id)+'?invite=1', done=function(){toast('Ссылка скопирована');};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(v).then(done).catch(function(){fallback(v,done);});else fallback(v,done); }
  function fallback(v,done){var i=document.createElement('input');i.value=v;i.style.position='fixed';i.style.opacity='0';document.body.appendChild(i);i.select();try{document.execCommand('copy');}catch(_){}i.remove();done();}
  function tab(t,replace){var a=['feed','schedule','films','members','stats','settings'];if(a.indexOf(t)<0||(t==='settings'&&!state.admin))t='feed';state.tab=t;try{history[replace?'replaceState':'pushState']({clubTab:t},'',location.pathname+location.search+(t==='feed'?'':'#'+t));}catch(_){}render();}
  function bind(){root.querySelectorAll('[data-club-tab]').forEach(function(b){b.onclick=function(){tab(b.getAttribute('data-club-tab'));};});root.querySelectorAll('[data-club-tab-jump]').forEach(function(b){b.onclick=function(){tab(b.getAttribute('data-club-tab-jump'));};});root.querySelectorAll('[data-club-join]').forEach(function(b){b.onclick=join;});root.querySelectorAll('[data-club-share],[data-club-copy]').forEach(function(b){b.onclick=copy;});}
  function load(id){state.id=String(id);root.innerHTML='<div class="club-loading" role="status">Загружаем киноклуб…</div>';var pub=req('/api/public/cinema-clubs?limit=100&offset=0').then(function(d){return arr(d,['groups','items','clubs']).find(function(x){return String(x&&(x.chat_id||x.id))===state.id;});});var mem=hasToken()&&typeof global.api==='function'?global.api('/api/site/rooms/'+encodeURIComponent(state.id)+'/members').catch(function(){return {}; }):Promise.resolve({});return Promise.all([pub,mem]).then(function(r){if(!r[0]&&hasToken()&&typeof global.api==='function')return global.api('/api/site/groups/discover?kind=cinema_club&discoverable_only=0&limit=100').then(function(d){return [arr(d,['groups','items']).find(function(x){return String(x&&(x.chat_id||x.id))===state.id;}),r[1]];});return r;}).then(function(r){if(!r[0])throw new Error('Киноклуб не найден');state.club=norm(r[0]);state.members=arr(r[1],['members','items','users']);detect();render();}).catch(function(e){root.innerHTML=empty('Не удалось открыть клуб',e&&e.message==='Киноклуб не найден'?'Проверьте ссылку или вернитесь в каталог киноклубов.':'Попробуйте обновить страницу позже.');});}
  function mount(id){root=document.getElementById('club-page-root');if(!root||!id)return;var h=String(location.hash||'').replace(/^#\/?/,'');state.tab=h||'feed';load(id);}
  function boot(){var m=String(location.pathname||'').match(/^\/club\/(-?\d+)\/?$/);if(m)mount(m[1]);}
  global.MPClubPage={mount:mount,reload:function(){if(state.id)load(state.id);}};
  window.addEventListener('hashchange',function(){if(state.id)tab(String(location.hash||'').replace(/^#\/?/,'')||'feed',true);});
  window.addEventListener('popstate',function(){var m=String(location.pathname||'').match(/^\/club\/(-?\d+)\/?$/);if(m){if(m[1]!==state.id)mount(m[1]);else tab(String(location.hash||'').replace(/^#\/?/,'')||'feed',true);}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
})(window);
